/* DO NOT EDIT THIS FILE */

#include <math.h>

#include "color.h"


unsigned int color_get_interval(float max) {
    if (max < 4.0f) {
        return 1;
    } else {
        return (int)max / 4.0f;
    }
}

float color_get_interval_inverse(float max) {
    return 1.0 / color_get_interval(max);
}
# pragma omp declare simd
void color_value(pixel_t* pixel, float value, int interval, float interval_inverse) {
    if (isnan(value)) {
        *pixel = pixel_black;
        goto done;
    }

    int x = (((int)value % interval) * 255) * interval_inverse;
    int i = value * interval_inverse;

    switch (i) {
    case 0:
        pixel->bytes[0] = 0;
        pixel->bytes[1] = x;
        pixel->bytes[2] = 255;
        break;
    case 1:
        pixel->bytes[0] = 0;
        pixel->bytes[1] = 255;
        pixel->bytes[2] = 255 - x;
        break;
    case 2:
        pixel->bytes[0] = x;
        pixel->bytes[1] = 255;
        pixel->bytes[2] = 0;
        break;
    case 3:
        pixel->bytes[0] = 255;
        pixel->bytes[1] = 255 - x;
        pixel->bytes[2] = 0;
        break;
    case 4:
        pixel->bytes[0] = 255;
        pixel->bytes[1] = 0;
        pixel->bytes[2] = x;
        break;
    default:
        *pixel = pixel_white;
        break;
    }

done:
    //*pixel = pixel_value;
}
