/* DO NOT EDIT THIS FILE */

#include <limits.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <GL/glut.h>

#include "headless.h"
#include "log.h"
#include "opencl.h"
#include "sinoscope.h"
#include "viewer.h"

static void show_help(FILE* f, const char* exec_name) {
    fprintf(f, "Usage: %s [OPTION]...\n", exec_name);
    fprintf(f, "\n");
    fprintf(f, "Options:\n");
    fprintf(f,
            "  --method [serial|openmp|opencl] computation method to use "
            "(default: serial)\n");
    fprintf(f,
            "  --width N                       width of the simulation "
            "(default: 512)\n");
    fprintf(f,
            "  --height N                      height of the simulation "
            "(default: 512)\n");
    fprintf(f,
            "  --taylor N                      degree of the taylor "
            "polynomial (default: 6)\n");
    fprintf(f,
            "  --opencl-platform N             opencl platform index to use "
            "(default: 0)\n");
    fprintf(f,
            "  --opencl-device N               opencl device index to use "
            "(default: 0)\n");
    fprintf(f,
            "  --opencl-kernel FILE            use a custom opencl kernel "
            "location\n");
    fprintf(f,
            "  --headless                      run the computation without "
            "graphical interface\n");
    fprintf(f,
            "  --save FILE                     save a frame into a PNG image\n");
    fprintf(f, "  --benchmark N                   benchmark all implementations for N iterations\n");
    fprintf(f, "  --check                         check openmp and opencl outputs\n");
    fprintf(f, "  --help                          show this help\n");
}

static void fail_missing_argument(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: option '%s' requires an argument\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_unknown_argument(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: unrecognized option '%s'\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_unknown_method(const char* exec_name, const char* arg) {
    fprintf(stderr, "%s: unrecognized argument '%s' for option `--method`\n", exec_name, arg);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_multiple_method(const char* exec_name) {
    fprintf(stderr, "%s: zero or one option `--method` must be specified\n", exec_name);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_argument_parsing(const char* exec_name, const char* arg_name, const char* arg) {
    fprintf(stderr, "%s: failed to parse '%s' for argument `%s`\n", exec_name, arg, arg_name);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_argument_require_positive(const char* exec_name, const char* arg_name) {
    fprintf(stderr, "%s: argument `%s` requires a positive number\n", exec_name, arg_name);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static unsigned int get_strictly_positive_integer_or_fail(const char* exec_name, const char* arg_name,
                                                          const char* arg) {
    long int value = strtol(arg, NULL, 10);
    if (value == LONG_MIN || value == LONG_MAX) {
        fail_argument_parsing(exec_name, arg_name, arg);
    }

    if (value <= 0) {
        fail_argument_require_positive(exec_name, arg_name);
    }

    return value;
}

static unsigned int get_positive_integer_or_fail(const char* exec_name, const char* arg_name, const char* arg) {
    long int value = strtol(arg, NULL, 10);
    if (value == LONG_MIN || value == LONG_MAX) {
        fail_argument_parsing(exec_name, arg_name, arg);
    }

    if (value < 0) {
        fail_argument_require_positive(exec_name, arg_name);
    }

    return value;
}

static void run_headless(sinoscope_t* sinoscope) {
    if (headless_run(sinoscope) < 0) {
        LOG_ERROR("failed to run headless");
        exit(1);
    }
}

static void run_benchmark(sinoscope_opencl_t* opencl, unsigned int width, unsigned int height, unsigned int taylor,
                          float max, unsigned int iterations) {
    if (sinoscope_benchmark(width, height, taylor, max, opencl, iterations) < 0) {
        LOG_ERROR("failed to check ouputs");
        exit(1);
    }
}

static void run_check(sinoscope_opencl_t* opencl, unsigned int width, unsigned int height, unsigned int taylor,
                      float max) {
    if (sinoscope_check(width, height, taylor, max, opencl) < 0) {
        LOG_ERROR("failed to check ouputs");
        exit(1);
    }
}

static void run_viewer(sinoscope_t* sinoscope) {
    if (viewer_init(sinoscope) < 0) {
        LOG_ERROR("failed to initialise viewer");
        exit(1);
    }

    if (viewer_open() < 0) {
        LOG_ERROR("failed to open viewer");
        exit(1);
    }

    viewer_destroy();
}

static sinoscope_opencl_t* configure_opencl(unsigned int platform, unsigned int device, sinoscope_opencl_t* opencl,
                                            unsigned int width, unsigned int height) {
    cl_device_id device_id;
    if (opencl_get_device_id(platform, device, &device_id) < 0) {
        LOG_ERROR("failed to get device ID");
        goto fail_exit;
    }

    if (opencl_print_device_info(device_id) < 0) {
        LOG_ERROR("failed to print opencl device information");
        goto fail_exit;
    }

    if (sinoscope_opencl_init(opencl, device_id, width, height) < 0) {
        LOG_ERROR("failed to initialize OpenCL context");
        goto fail_exit;
    }

    return opencl;

fail_exit:
    printf("Disabling OpenCL support\n");
    return NULL;
}

int main(int argc, char* argv[]) {
    if (getenv("DISPLAY") != NULL) {
        glutInit(&argc, argv);
    }

    char* exec_name        = argv[0];
    bool use_method_serial = false;
    bool use_method_openmp = false;
    bool use_method_opencl = false;
    int use_method_count   = 0;
    bool do_run_headless   = false;
    bool do_benchmark      = false;
    bool do_check          = false;
    bool do_save_image     = false;

    char* save_filename = NULL;

    unsigned int width      = 512;
    unsigned int height     = 512;
    unsigned int taylor     = 6;
    unsigned int iterations = 0;

    unsigned int opencl_platform_index = 0;
    unsigned int opencl_device_index   = 0;

    for (int i = 1; i < argc; i++) {
        if (strcmp("--method", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            if (strcmp("serial", argv[i + 1]) == 0) {
                use_method_serial = true;
                use_method_count++;
            } else if (strcmp("openmp", argv[i + 1]) == 0) {
                use_method_openmp = true;
                use_method_count++;
            } else if (strcmp("opencl", argv[i + 1]) == 0) {
                use_method_opencl = true;
                use_method_count++;
            } else {
                fail_unknown_method(exec_name, argv[i + 1]);
            }

            i++;
        } else if (strcmp("--width", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            width = get_strictly_positive_integer_or_fail(exec_name, argv[i], argv[i + 1]);
            i++;
        } else if (strcmp("--height", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            height = get_strictly_positive_integer_or_fail(exec_name, argv[i], argv[i + 1]);
            i++;
        } else if (strcmp("--taylor", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            taylor = get_strictly_positive_integer_or_fail(exec_name, argv[i], argv[i + 1]);
            i++;
        } else if (strcmp("--opencl-platform", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            opencl_platform_index = get_positive_integer_or_fail(exec_name, argv[i], argv[i + 1]);
            i++;
        } else if (strcmp("--opencl-device", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            opencl_device_index = get_positive_integer_or_fail(exec_name, argv[i], argv[i + 1]);
            i++;
        } else if (strcmp("--opencl-kernel", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            opencl_kernel_path = argv[i + 1];
            i++;
        } else if (strcmp("--headless", argv[i]) == 0) {
            do_run_headless = true;
        } else if (strcmp("--save", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            do_save_image = true;
            save_filename = argv[i + 1];
            i++;
        } else if (strcmp("--benchmark", argv[i]) == 0) {
            if (i >= argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            iterations = get_strictly_positive_integer_or_fail(exec_name, argv[i], argv[i + 1]);
            i++;

            do_benchmark = true;
        } else if (strcmp("--check", argv[i]) == 0) {
            do_check = true;
        } else if (strcmp("--help", argv[i]) == 0) {
            show_help(stdout, exec_name);
            exit(0);
        } else {
            fail_unknown_argument(exec_name, argv[i]);
        }
    }

    sinoscope_t* sinoscope = NULL;
    sinoscope_opencl_t sinoscope_opencl;
    sinoscope_opencl_t* sinoscope_opencl_ptr =
        configure_opencl(opencl_platform_index, opencl_device_index, &sinoscope_opencl, width, height);

    if (do_benchmark) {
        run_benchmark(sinoscope_opencl_ptr, width, height, taylor, 200.0, iterations);
        goto done;
    }

    if (do_check) {
        run_check(sinoscope_opencl_ptr, width, height, taylor, 200.0);
        goto done;
    }

    if (use_method_count == 0) {
        use_method_serial = true;
    } else if (use_method_count > 1) {
        fail_multiple_method(exec_name);
    }

    if (use_method_serial) {
        sinoscope = sinoscope_create("serial", sinoscope_image_serial, width, height, 200.0);
    } else if (use_method_openmp) {
        sinoscope = sinoscope_create("openmp", sinoscope_image_openmp, width, height, 200.0);
    } else if (use_method_opencl) {
        sinoscope = sinoscope_create("opencl", sinoscope_image_opencl, width, height, 200.0);
    } else {
        LOG_ERROR("no method defined");
        exit(1);
    }

    if (sinoscope == NULL) {
        LOG_ERROR("failed to create sinoscope");
        exit(1);
    }

    sinoscope->opencl = sinoscope_opencl_ptr;
    sinoscope->taylor = taylor;

    if (getenv("DISPLAY") == NULL) {
        printf("DISPLAY environment variable not set, forcing headless mode\n");
        do_run_headless = true;
    }

    if (do_save_image) {
        if (sinoscope_save_image(sinoscope, save_filename) < 0) {
            LOG_ERROR("failed to save image");
            exit(1);
        }

        goto done;
    }

    if (do_run_headless) {
        run_headless(sinoscope);
    } else {
        run_viewer(sinoscope);
    }

done:
    if (sinoscope_opencl_ptr != NULL) {
        sinoscope_opencl_cleanup(sinoscope_opencl_ptr);
    }

    if (sinoscope != NULL) {
        sinoscope_destroy(sinoscope);
    }

    return 0;
}
